---
abstract: ~
author:
  - 'Errietta Kostala <e.kostala@shadowcat.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Authentication-Credential-GooglePlus
no_index:
  directory:
    - inc
requires:
  Crypt::OpenSSL::RSA: 0
  Crypt::OpenSSL::X509: 0
  Date::Parse: 0
  IO::All: 0
  JSON::MaybeXS: 0
  JSON::WebToken: 0
  LWP::Protocol::https: 0
  LWP::Simple: 0
  MIME::Base64: 0
  Try::Tiny: 0
  strictures: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
